name: Deploy to EC2

on:
  push:
    branches:
      - main  # or 'master'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          git pull origin main
          docker stop $(docker ps -q)
          docker rm $(docker ps -aq)
          docker build -t flask-devops-app .
          docker run -d -p 5000:5000 flask-devops-app
